services:
  postgres-db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: devops_user
      POSTGRES_PASSWORD: devops_password
      POSTGRES_DB: devops_app_db
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devops_user -d devops_app_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: ${DOCKER_HUB_USERNAME}/fullstack-backend:latest
    build:
      context: ./backend/backend
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: postgres
      DB_URL: jdbc:postgresql://postgres-db:5432/devops_app_db
      DB_USERNAME: devops_user
      DB_PASSWORD: devops_password
    ports:
      - "8081:8081"
    depends_on:
      postgres-db:
        condition: service_healthy

  frontend:
    image: ${DOCKER_HUB_USERNAME}/fullstack-frontend:latest
    build:
      context: ./Frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  db_data:
