import { useEffect, useMemo, useState } from "react";
import "./App.css";
import { createStudent, deleteStudent, getStudents, updateStudent } from "./services/studentService";

const teachers = [
  ["Mr. Ramesh Kumar Yadav", "Principal", "M.Ed. · English Education", "English", "RY", "coral"],
  ["Mrs. Sunita Chaudhary", "Vice Principal", "M.Sc. · Mathematics", "Mathematics", "SC", "blue"],
  ["Mr. Deepak Kumar Sah", "Senior Teacher", "M.Sc. · Physics", "Science", "DS", "gold"],
  ["Mrs. Anita Jha", "Primary Coordinator", "M.A. · B.Ed.", "Social Studies", "AJ", "green"],
  ["Ms. Priyanka Mandal", "Pre-primary Lead", "B.Ed. · Montessori Trained", "Early Learning", "PM", "purple"],
  ["Mr. Santosh Mahato", "ICT Teacher", "B.Sc. CSIT", "Computer Science", "SM", "teal"],
].map(([name, role, qualification, subject, initials, color]) => ({ name, role, qualification, subject, initials, color }));
const classNames = ["Nursery", "LKG", "UKG", ...Array.from({ length: 10 }, (_, i) => `Class ${i + 1}`)];
const emptyStudent = { studentId: "", name: "", className: "Nursery", guardian: "", phone: "", location: "" };
const programs = [
  ["✦", "AGES 3–5", "Early Years", "A joyful start through stories, play, discovery and friendship.", "sun"],
  ["⌁", "CLASSES 1–5", "Primary School", "Strong foundations with curiosity, creativity and confident communication.", "sky"],
  ["↗", "CLASSES 6–10", "Secondary School", "Focused academics, life skills and preparation for every next step.", "leaf"],
];

function Icon({ name, size = 20 }) {
  const p = { menu: <path d="M4 7h16M4 12h16M4 17h16"/>, close: <path d="m6 6 12 12M18 6 6 18"/>, arrow: <><path d="M5 12h14M14 7l5 5-5 5"/></>, users: <><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75"/></>, phone: <path d="M22 16.9v3a2 2 0 0 1-2.2 2 19.8 19.8 0 0 1-8.6-3.1 19.5 19.5 0 0 1-6-6A19.8 19.8 0 0 1 2.1 4.2 2 2 0 0 1 4.1 2h3a2 2 0 0 1 2 1.7c.1 1 .4 1.9.7 2.8a2 2 0 0 1-.5 2.1L8.1 9.9a16 16 0 0 0 6 6l1.3-1.3a2 2 0 0 1 2.1-.4c.9.3 1.8.6 2.8.7a2 2 0 0 1 1.7 2Z"/>, pin: <><path d="M20 10c0 5-8 12-8 12S4 15 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/></>, search: <><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></> };
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{p[name]}</svg>;
}

export default function App() {
  const [menuOpen, setMenuOpen] = useState(false), [directoryOpen, setDirectoryOpen] = useState(false), [selectedClass, setSelectedClass] = useState("Nursery"), [search, setSearch] = useState(""), [formStatus, setFormStatus] = useState("");
  const [students, setStudents] = useState([]), [studentForm, setStudentForm] = useState(emptyStudent), [editingId, setEditingId] = useState(null), [manageOpen, setManageOpen] = useState(false), [studentStatus, setStudentStatus] = useState("Loading students…");
  useEffect(() => { document.body.style.overflow = directoryOpen ? "hidden" : ""; return () => { document.body.style.overflow = ""; }; }, [directoryOpen]);
  useEffect(() => { getStudents().then(data => { setStudents(data); setStudentStatus(""); }).catch(() => setStudentStatus("Start the backend server to load and manage students.")); }, []);
  const visibleStudents = useMemo(() => students.filter(s => s.className === selectedClass && `${s.studentId ?? ""} ${s.name} ${s.guardian} ${s.location}`.toLowerCase().includes(search.toLowerCase())), [students, selectedClass, search]);
  const scrollTo = id => { document.getElementById(id)?.scrollIntoView({ behavior: "smooth" }); setMenuOpen(false); };
  const openAddStudent = () => { setEditingId(null); setStudentForm({ ...emptyStudent, className: selectedClass }); setStudentStatus(""); setManageOpen(true); };
  const openEditStudent = student => { setEditingId(student.id); setStudentForm({ studentId: student.studentId ?? "", name: student.name, className: student.className, guardian: student.guardian, phone: student.phone, location: student.location }); setStudentStatus(""); setManageOpen(true); };
  const saveStudent = async event => { event.preventDefault(); setStudentStatus(editingId ? "Saving changes…" : "Adding student…"); try { const saved = editingId ? await updateStudent(editingId, studentForm) : await createStudent(studentForm); setStudents(current => editingId ? current.map(s => s.id === saved.id ? saved : s) : [...current, saved]); setSelectedClass(saved.className); setManageOpen(false); setStudentStatus(editingId ? "Student updated successfully." : "Student added successfully."); } catch { setStudentStatus("Could not save. Make sure the backend and database are running."); } };
  const removeStudent = async student => { if (!window.confirm(`Delete ${student.name} from ${student.className}?`)) return; setStudentStatus("Deleting student…"); try { await deleteStudent(student.id); setStudents(current => current.filter(s => s.id !== student.id)); setStudentStatus("Student deleted successfully."); } catch { setStudentStatus("Could not delete the student. Please check the backend."); } };
  return <div className="site-shell">
    <header className="site-header"><button className="brand" onClick={() => scrollTo("home")}><span className="brand-badge">SP</span><span><strong>Salhesh Phoolwari</strong><small>ENGLISH BOARDING SCHOOL</small></span></button><nav className={menuOpen ? "nav open" : "nav"}>{[["Home","home"],["About","about"],["Academics","academics"],["Teachers","teachers"]].map(x => <button key={x[0]} onClick={() => scrollTo(x[1])}>{x[0]}</button>)}<button onClick={() => setDirectoryOpen(true)}>Students</button></nav><div className="header-actions"><button className="directory-button" onClick={() => setDirectoryOpen(true)}><Icon name="users" size={17}/> Student directory</button><button className="menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle navigation"><Icon name={menuOpen ? "close" : "menu"}/></button></div></header>
    <main>
      <section className="hero" id="home"><div className="hero-photo"/><div className="hero-overlay"/><div className="hero-copy"><div className="trust-pill"><span>★</span> Learning with joy since 2004</div><h1>Little steps.<br/><em className="premium-word">Bright futures.</em></h1><p>A caring school community where every child from Nursery to Class 10 is encouraged to learn bravely, grow kindly and dream big.</p><div className="hero-actions"><button className="primary" onClick={() => scrollTo("admission")}>Explore admission <Icon name="arrow"/></button><button className="secondary" onClick={() => setDirectoryOpen(true)}>Meet our students</button></div></div><div className="hero-card"><span className="card-icon">✦</span><div><strong>Admissions open</strong><p>For academic session 2083</p></div><button onClick={() => scrollTo("admission")}><Icon name="arrow"/></button></div><div className="scribble one">Learn</div><div className="scribble two">Grow</div></section>
      <section className="welcome section" id="about"><div className="welcome-label"><span>01</span><i/></div><div><p className="eyebrow">WELCOME TO OUR SCHOOL</p><h2>A happy place to<br/><em className="premium-word">learn and belong.</em></h2></div><div className="welcome-copy"><p>At Salhesh Phoolwari, education means more than lessons. It means discovering confidence, caring for others and building the skills to thrive in tomorrow’s world.</p><div className="mini-stats"><span><strong>22+</strong>Years of learning</span><span><strong>500+</strong>Happy students</span><span><strong>28</strong>Caring teachers</span></div></div></section>
      <section className="academics section" id="academics"><SectionTitle eyebrow="A JOURNEY FOR EVERY AGE" title={<>Learning that grows<br/>with your child.</>} text="Thoughtfully designed learning stages build strong foundations and prepare students for meaningful futures."/><div className="program-grid">{programs.map(([icon, grade, title, text, tone], i) => <article className={`program ${tone}`} key={title}><span className="program-number">0{i+1}</span><div className="program-icon">{icon}</div><small>{grade}</small><h3>{title}</h3><p>{text}</p><button onClick={() => scrollTo("admission")}>Learn more <Icon name="arrow" size={17}/></button></article>)}</div></section>
      <section className="teachers section" id="teachers"><SectionTitle eyebrow="THE HEART OF OUR SCHOOL" title={<>Teachers who see<br/>the best in every child.</>} text="Qualified, approachable educators who make every classroom feel safe, active and inspiring."/><div className="teacher-grid">{teachers.map(t => <article className="teacher-card" key={t.name}><div className={`teacher-portrait ${t.color}`}><span>{t.initials}</span><i>✦</i></div><div className="teacher-info"><span>{t.role}</span><h3>{t.name}</h3><p>{t.qualification}</p><small>{t.subject}</small></div></article>)}</div></section>
      <section className="directory-promo"><div className="promo-art"><span>अ</span><span>Aa</span><span>१</span><div>Every child<br/>matters here.</div></div><div className="promo-copy"><p className="eyebrow">OUR SCHOOL FAMILY</p><h2>Find your class.<br/><em className="premium-word premium-word--dark">Meet your friends.</em></h2><p>Browse students from Nursery through Class 10. Choose a class to view student names, guardian contact numbers and locations.</p><button className="light-button" onClick={() => setDirectoryOpen(true)}><Icon name="users"/> Open student directory <Icon name="arrow"/></button></div></section>
      <section className="admission section" id="admission"><div><p className="eyebrow">ADMISSIONS 2083</p><h2>Your child’s bright<br/><span className="premium-word">journey starts here.</span></h2><p>Visit our school, meet our teachers and discover a learning environment your child will love.</p><div className="contact-line"><span><Icon name="phone"/></span><div><small>CALL FOR ADMISSION</small><strong>+977 980-0000000</strong></div></div></div><form onSubmit={e => { e.preventDefault(); setFormStatus("Thank you! Our admission team will contact you soon."); e.currentTarget.reset(); }}><h3>Request a school visit</h3><label>Parent / guardian name<input required placeholder="Your full name"/></label><label>Phone number<input required type="tel" placeholder="98XXXXXXXX"/></label><label>Admission for<select defaultValue=""><option value="" disabled>Select a class</option>{classNames.map(n => <option key={n}>{n}</option>)}</select></label><button className="primary">Send request <Icon name="arrow"/></button>{formStatus && <p className="form-status">{formStatus}</p>}</form></section>
    </main>
    <footer><div className="footer-brand"><span className="brand-badge">SP</span><div><strong>Salhesh Phoolwari</strong><small>ENGLISH BOARDING SCHOOL</small></div></div><p>Knowledge · Character · Confidence</p><span>© 2026 Salhesh Phoolwari School</span></footer>
    {directoryOpen && <div className="directory-modal" role="dialog" aria-modal="true">
      <div className="directory-head"><div><p className="eyebrow">SALHESH PHOOLWARI SCHOOL</p><h2>Student directory</h2><p>Add, edit or delete students from Nursery through Class 10.</p></div><button className="close-button" onClick={() => setDirectoryOpen(false)} aria-label="Close"><Icon name="close"/></button></div>
      <div className="directory-layout"><aside><strong>Choose a class</strong><div className="class-list">{classNames.map(n => <button className={selectedClass === n ? "active" : ""} onClick={() => {setSelectedClass(n);setSearch("");setManageOpen(false);}} key={n}><span>{n}</span><small>{students.filter(s => s.className === n).length} students</small><Icon name="arrow" size={16}/></button>)}</div></aside>
        <section className="student-panel">
          <div className="student-toolbar"><div><span>Selected class</span><h3>{selectedClass}</h3></div><div className="toolbar-actions"><label className="search"><Icon name="search" size={18}/><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search ID, student or location"/></label><button className="add-student" onClick={openAddStudent}>+ Add student</button></div></div>
          {manageOpen && <form className="student-form" onSubmit={saveStudent}><div className="form-heading"><div><small>{editingId ? "UPDATE RECORD" : "NEW STUDENT"}</small><h3>{editingId ? "Edit student details" : `Add student to ${selectedClass}`}</h3></div><button type="button" onClick={() => setManageOpen(false)} aria-label="Close form"><Icon name="close" size={18}/></button></div><div className="student-fields"><label>Student ID<input required maxLength="30" value={studentForm.studentId} onChange={e => setStudentForm({...studentForm,studentId:e.target.value})} placeholder="Example: SP-2083-001"/></label><label>Student name<input required value={studentForm.name} onChange={e => setStudentForm({...studentForm,name:e.target.value})} placeholder="Full name"/></label><label>Class<select required value={studentForm.className} onChange={e => setStudentForm({...studentForm,className:e.target.value})}>{classNames.map(n => <option key={n}>{n}</option>)}</select></label><label>Parent / guardian<input required value={studentForm.guardian} onChange={e => setStudentForm({...studentForm,guardian:e.target.value})} placeholder="Guardian name"/></label><label>Family number<input required type="tel" inputMode="numeric" maxLength="10" pattern="98[0-9]{8}" title="Enter exactly 10 digits starting with 98" value={studentForm.phone} onChange={e => setStudentForm({...studentForm,phone:e.target.value.replace(/\D/g, "").slice(0, 10)})} placeholder="98XXXXXXXX"/></label><label>Location<input required value={studentForm.location} onChange={e => setStudentForm({...studentForm,location:e.target.value})} placeholder="Example: Lahan-5"/></label></div><div className="form-actions"><button type="button" onClick={() => setManageOpen(false)}>Cancel</button><button className="primary" type="submit">{editingId ? "Save changes" : "Add student"}</button></div></form>}
          {studentStatus && <p className="student-status" role="status">{studentStatus}</p>}
          <div className="student-table"><div className="table-row table-head"><span>Student</span><span>Parent / guardian</span><span>Family number</span><span>Location</span><span>Actions</span></div>{visibleStudents.map((s,i) => <div className="table-row" key={s.id}><span className="student-name"><i>{String(i+1).padStart(2,"0")}</i><span><strong>{s.name}</strong><small>{s.studentId || "No student ID"}</small></span></span><span>{s.guardian}</span><span><a href={`tel:${s.phone}`}>{s.phone}</a></span><span><Icon name="pin" size={15}/>{s.location}</span><span className="row-actions"><button onClick={() => openEditStudent(s)}>Edit</button><button className="delete" onClick={() => removeStudent(s)}>Delete</button></span></div>)}{!visibleStudents.length && !studentStatus && <div className="empty-state">No students in {selectedClass}. Click “Add student” to create one.</div>}</div><p className="privacy-note">Protect real student and family details with secure administrator login before publishing this directory.</p>
        </section>
      </div>
    </div>}
  </div>;
}
function SectionTitle({ eyebrow, title, text }) { return <div className="section-title"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div><p>{text}</p></div>; }
